### ISSUE TITLE
Remove Search Relevance Question on Collections pages

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1010]
## Problem

CC Search has specific Collections page, such as https://search.creativecommons.org/collections/met

The only way for a user to navigate to this page is via the Collections tab. When a user first lands on it, we simply load all images from within that collection. At this point a user has not entered a search query. As such, we should **not** be showing our question, "Are these results relevant?", on that page.

## Solution

We'd like to remove our search relevance question from the first page of the Collections results.
<img width="1107" alt="relevance question on collections page" src="https://user-images.githubusercontent.com/3051816/84173207-7dae8280-aa6c-11ea-86dd-87c6737e34e3.png">

It should be noted that after a user enters a search query to search within a Collection, we'd like to keep the question present there, e.g.:
<img width="1098" alt="results relevance - search within collections" src="https://user-images.githubusercontent.com/3051816/84173047-4213b880-aa6c-11ea-80fd-34b7b4a50c0e.png">

At that point, it is important for us to gather relevance data in relation to their query.

**Comment by annatuma** [comment]
Tagging @aldenstpage to review this suggested change. I want to ensure we're not missing something on how we gather the data on relevance (e.g. if we should include the Collections page if a user is within it?).

**Comment by aldenstpage** [comment]
This is a good question. We designed the analytics API around the `q` parameter (what the user types in the search box), and since there is no query on the collections page, clicking the button in this context will not record anything useful.

The analytics API was designed before we even had a browse-by-collections view, if I'm remembering correctly, so it was not designed for this purpose. We should either remove it from the collections page entirely or update the analytics API to collect more information (such as whether it is being triggered on a collections page, which filters are in place, etc). IMO the right thing to do is to just remove it.
