### ISSUE TITLE
Feature: Progressive Web App 

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#1020]
Implement Progressive Web App for CC Search

We can make both mobile and web as a progressive app! (Add App to Home Screen)

- Mobile Compatible

- Desktop Compatible(If Needed)

Most of the apps nowadays are sunsetting their mobile web apps and going full PWA like:
`DRIBBLE:`

![driible-pwa](https://user-images.githubusercontent.com/55599878/84836075-b1803e00-b052-11ea-827a-ff32829d637e.jpg)

`TWITTER:`

![twitter-pwa](https://user-images.githubusercontent.com/55599878/84836101-ba710f80-b052-11ea-90a5-50cfb45a9d2a.jpg)

**Comment by kgodey** [comment]
@abhisheknaiidu new features have to go through @annatuma for triage so I added "awaiting triage" back. Please talk with her directly and get her approval before removing the label.

**Comment by annatuma** [comment]
Thanks for the suggestion @abhisheknaiidu 

While I agree that PWAs are nifty, and may be appropriate for some apps, I'm not convinced that this would be the right move for CC Search, and definitely not in the short term.

We'd need to start by doing user research to understand if there was even a need for this. Assuming there was, we'd need to look into what is feasible for us to load offline for users, while being cognizant of storage space, amongst other things. Further, it would likely require a different definition of the product entirely, since the goal of PWAs is typically to build engagement with the product, while we explicitly steer users _through_ CC Search, treating it as a portal, and send them on to their destinations of sites containing CC licensed content.

That said, the scenario may change in time. I'm going to put this in the parking lot for now and mark it as blocked. That way, anyone with a similar idea can contribute to the discussion here.

**Comment by KarenEfereyan** [comment]
PWAs? Seems interesting
