### ISSUE TITLE
Improve related image results on photo detail page

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#123]
It looks like related images are generated from a search of the first tag in the image. At a minimum, this should reuse the user's search query instead of a random tag.

We could also off-load this functionality to the backend and develop an /image/{id}/related endpoint if we need something more sophisticated than that. I'll bring this up during our standup on Monday.

**Comment by aldenstpage** [comment]
There should be a backend API endpoint for this. We can use Elasticsearch's "More Like This" query. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

**Comment by manyaagarwal** [comment]
Can I work on this issue?

**Comment by aldenstpage** [comment]
Absolutely!

**Comment by kgodey** [comment]
@brenoferreira as a short term fix, could you updated the related images API call to use the image search endpoint with the original search term instead of looking for images with the same first tag?

I made a separate issue for the longer term fix of adding a related images endpoint to the API: https://github.com/creativecommons/cccatalog-api/issues/286
