### ISSUE TITLE
A/B test language on donation banner

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1233]
Suggestions welcome in the comments.

Something like:
"Only X% of people reading this will donate. Be one of them and help us sustain CC Search."

Look at our stats to glean what the X% is since launching just under a week ago.

**Comment by zackkrida** [comment]
From sep 24th to october 5th, we've had 128,347 users and 902 clicks. So we could round up to 1%. Does that sound too bleak?

Proposed copy:

> "Only 1% of people reading this will donate. Be one of them and help us sustain CC Search."

**Comment by zackkrida** [comment]
@obulat Notes on setting up an ab test:

In [this PR](https://github.com/creativecommons/cccatalog-frontend/pull/1073/files) I _converted_ one A/B test into a new one, but your work to create a new one would be similar:

Create a new file in the `src/abTests/experiments` directory, with this signature:

```js
const EXPERIMENT_NAME = 'experiment_name'
const EXPERIMENT_CASE_A = 'case_a'
const EXPERIMENT_CASE_B = 'case_b'

/**
 * Joins the experiment.
 *
 * Returns a Promise, which resolves with the experiment name and selected experiment case.
 * In case of failure, it rejects with the error, the experiment name and a default experiment case
 * @param {*} session Sixpack session object
 */
const joinExperiment = (session) => {
  const resultPromise = new Promise((resolve, reject) => {
    session.participate(
      EXPERIMENT_NAME,
      [EXPERIMENT_CASE_A, EXPERIMENT_CASE_B],
      (err, res) => {
        if (err || res.error) {
          reject({
            error: err,
            name: EXPERIMENT_NAME,
            case: EXPERIMENT_CASE_A, // whichever case should be default goes here
            session,
          })
        }

        const experimentCase = res.alternative.name

        resolve({
          name: EXPERIMENT_NAME,
          case: experimentCase,
          session,
        })
      }
    )
  })

  return resultPromise
}

export default joinExperiment
export const ExperimentData = {
  EXPERIMENT_NAME,
  EXPERIMENT_CASE_A,
  EXPERIMENT_CASE_B,
}

```

Then you need to import the experiment here: https://github.com/creativecommons/cccatalog-frontend/blob/fd4bdb7297cc1ba81c56aa2d21b6e4062e1acfbf/src/abTests/index.js

Finally, you can read which version of the experiment is active inside of a vue component. Here's a silly example, where we check if 'case a' is active:

```js
<template>
	<div>
		<div v-if="isCaseA">Experiment A is active!</div>
		<div v-else>Experiment B is active!</div>
	</div>
</template>

<script>
import { ExperimentData } from '@/abTests/experiments/yourExperimentHere'

export default {
	name: 'demo-component',
	computed: {
       isCaseA() {
		const experiment = this.$store.state.experiments.find(
          (exp) => exp.name === ExperimentData.EXPERIMENT_NAME
        )
        return experiment.case === ExperimentData.EXPERIMENT_CASE_A
       }
    }
}
</script>
```

**Comment by akmadian** [comment]
The first thing I thought of when I read this was the Wikipedia donation banner. Turns out that fewer than 1% of their users donate, too! Here's a picture of one of their banners:

![image](https://user-images.githubusercontent.com/28791774/95179856-0d8fdf00-0776-11eb-9a78-0820c509455a.png)

I also found this in the images for "wikipedia donation":

![image](https://user-images.githubusercontent.com/28791774/95179950-28faea00-0776-11eb-927e-d25f4a52a4a9.png)

It's a chart from [a Wikipedia blog post from 2012](https://diff.wikimedia.org/2012/02/05/who-are-wikipedias-donors/) so it's pretty outdated, but the most interesting parts to me are the top two reasons. Seems that an appeal from the founder goes a long way, and just making it known that donations are welcomed goes an even longer way : )
