### ISSUE TITLE
Need ability to search author or artist on Cleveland Art

### ISSUE THREAD

**Issue by little-wow** [creativecommons/cccatalog-frontend#166]
I think you can only search by title on the Cleveland Museum API.

See:

![img_d05cea2b16ec-1](https://user-images.githubusercontent.com/7093838/51616907-1df81b80-1ef9-11e9-8576-8ded0d0d6f47.jpeg)
![img_3bb0da964b73-1](https://user-images.githubusercontent.com/7093838/51616908-1df81b80-1ef9-11e9-9e74-539e31dc151d.jpeg)

**Comment by janeatcc** [comment]
yes, currently the algorithm only searches tags + title. something for us to discuss for next sprint on changing this up

**Comment by aldenstpage** [comment]
We used to include creator names in the search API, but it generally led to poor quality search results.

It's possible to filter results by creator right now using the `creator` parameter (currently unused by the frontend). ex: http://api.creativecommons.engineering/image/search?q=dancer;creator=degas . This is of limited usefulness because you still need to include a `q`uery string; you can't just search by creator. The frontend would also need to somehow know that the user is specifically searching for a creator; probably not possible unless we add a dedicated creator search bar.

I could look into a better creator search experience next sprint.

**Comment by janeatcc** [comment]
Can we only search across creator fields from some providers, e.g. from museums?
