### ISSUE TITLE
Creator name is weirdly formatted and not linked/clickable

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#181]
See for example: https://ccsearch.creativecommons.org/photos/966cfb20-5071-42d4-a70b-3faf961be5fc

Clicking on creator yields nothing as well

**Comment by brenoferreira** [comment]
Related to #192

**Comment by dhruvkb** [comment]
Although the creator name now appears correctly, the anchor tag on the creator name still points to null. This is not a frontend issue however, because the `cccatalog-api` models do not have a model field for storing the link to the creator profile and thus will not be able to supply that via the API.

**Comment by dhruvkb** [comment]
PR #219 addresses the linking in the creator name. Kindly review and let me know if it addresses the issue adequately.

**Comment by dhruvkb** [comment]
@janeatcc, you might want to close this issue.
