### ISSUE TITLE
Improvements to CC Search UI

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#229]
- [x] Change home page image
- [x] Improve UI of CC Search to make it look like CC homepage

**Comment by dhruvkb** [comment]
Instead of just changing the homepage image to something different, it could be wonderful if it displayed a new image from the CC repertoire on every visit or every day.

Even though @brenoferreira has been assigned to this issue, can I work on some aspects of this such as matching the CC search header and footer to the CC homepage?

**Comment by brenoferreira** [comment]
@dhruvkb we prefer if you choose another issue and refrain from on issues that are assigned to a project, in this case the `Active Sprint`

**Comment by dhruvkb** [comment]
@brenoferreira I had not noticed the project, I'm so very sorry.
