### ISSUE TITLE
Improve test coverage for components

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#232]
Write unit tests for the [components](https://github.com/creativecommons/cccatalog-frontend/tree/master/src/components) and [pages](https://github.com/creativecommons/cccatalog-frontend/tree/master/src/pages).

There are already [some components with unit tests](https://github.com/creativecommons/cccatalog-frontend/blob/master/test/unit/specs/components/photo-details.spec.js), please use them as guidelines for writing future tests

**Comment by sudharsana-kjl** [comment]
Hi! Can I work on this issue?

**Comment by kgodey** [comment]
Go ahead, could you post what components you'll be writing tests for in this issue?

**Comment by sudharsana-kjl** [comment]
I'd like to write tests for HeaderSection, PhotoTags, ShareList, CopyButton

**Comment by VatsalSin** [comment]
Hey @sudharsana-kjl, I was working on a issue related to image tags and hence have already added tests for PhotoTags in PR #226 to test the changes made .

**Comment by kgodey** [comment]
That sounds good, I'll remove the "in progress" tag in case someone else wants to work on tests for other components.

**Comment by catherinehoang** [comment]
Hi! I'm working on tests for LicenseIcons and HomePage

**Comment by brenoferreira** [comment]
Reopening because more tests are always welcome

**Comment by dhuang612** [comment]
cool, I would like to contribute to this

**Comment by kgodey** [comment]
Go ahead.

**Comment by AmanR28** [comment]
I would like to contribute here.

**Comment by AyanChoudhary** [comment]
I would like to write the tests for client side pages:BrowsePage, Collectionbrowsepage and photoDetailPage

**Comment by AyanChoudhary** [comment]
> I would like to write the tests for client side pages:BrowsePage, Collectionbrowsepage and photoDetailPage
@kgodey

**Comment by genedy377** [comment]
It's my pleasure to write the test part of the component : SearchGrid ,SearchGridCell , SearchGridForm,SearchGridFilter
thanks in advance

**Comment by kgodey** [comment]
go ahead @genedy377 @AyanChoudhary

**Comment by sheilaanguiano** [comment]
Hello,  
Since this is reopen, I'd like to know if I can help to make this my first contribution as part of the outreachy program

**Comment by brenoferreira** [comment]
@sheilaanguiano yes :)

**Comment by ruthstern** [comment]
Hi everyone, I would like to assist here too :-)

**Comment by ruthstern** [comment]
Is that still possible ? Kind regards

**Comment by AhmedSamir97** [comment]
My name is Ahmed Samir , I'd like to work on the test coverage for this project for the following component  SearchGridForm and SearchGridFilter can anyone help me ?

**Comment by AhmedSamir97** [comment]
also , photo tag and reuseSurvey

**Comment by akmadian** [comment]
Hey @ruthstern, go ahead! Please be sure to comment which component you intend to work on, and be sure to check to see if someone else is already working on it.

@AhmedSamir97 you can also help out, please check to see if someone else is working on tests for the same component you intend to work on before getting started :)

For both of you, if you are working on tests for multiple components (I would recommend working on a maximum of two at a time), please submit a single pull request for each component instead of multiple components per PR.

**Comment by TikuGaelle** [comment]
Hello, i would like to know if I can work on this issue as a first contribution to my outreachy program?

**Comment by devRD** [comment]
Hi! Can I work on this issue?

**Comment by akmadian** [comment]
@TikuGaelle @devRD go ahead! Please be sure to check which components already have tests being written for them before getting started.

For both of you, if you are working on tests for multiple components (I would recommend working on a maximum of two at a time), please submit a single pull request for each component instead of multiple components per PR.

**Comment by TikuGaelle** [comment]
> @TikuGaelle @devRD go ahead! Please be sure to check which components already have tests being written for them before getting started.
> 
> For both of you, if you are working on tests for multiple components (I would recommend working on a maximum of two at a time), please submit a single pull request for each component instead of multiple components per PR.

https://github.com/creativecommons/chooser/issues/122
@akmadian can i work on this?

**Comment by akmadian** [comment]
@TikuGaelle go ahead! Please be sure to check which components already have tests being written for them before getting started.

For both of you, if you are working on tests for multiple components (I would recommend working on a maximum of two at a time), please submit a single pull request for each component instead of multiple components per PR.

**Comment by Albaalah** [comment]
Hi, I would like to write tests for SearchHelpPage page and LoadingIcon component

**Comment by jansone-dace** [comment]
Hello!   
I will write tests for FilterChecklist component.

**Comment by boyrazs15** [comment]
Hi! Can I work on this issue? I would like to write the tests for HomeLicenseFilter component.

**Comment by enelesmai** [comment]
Hi! Can I contribute here? I would like to write the tests for SearchRating component.
