### ISSUE TITLE
multiple image grid bug

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#264]
<img width="1385" alt="Screen Shot 2019-04-01 at 3 55 47 PM" src="https://user-images.githubusercontent.com/6394777/55364744-b7622180-5496-11e9-9171-75b9aac5fc30.png">

When you click "prevent overscaling" and then unclick it, it results in the above, images together with no white spacing

_Originally posted by @janeatcc in https://github.com/creativecommons/cccatalog-frontend/issues/103#issuecomment-478776702_

**Comment by dhruvkb** [comment]
For anyone attempting to solve this issue, _myself included_, I've managed to locate the cause of the issue. Clicking the checkbox triggers a styling change on the cell components who take a small amount of time to recalculate their new height. Meanwhile the call to `$redrawVueMasonry()` gets executed with only a subset of cells having completed this recalculation, causing incorrect alignment.

A possible solution to the issue is this hack.
```js
setTimeout(() => {
  this.$redrawVueMasonry(); // Some elements end up taking less space
}, 1000); // One second should be sufficient to calculate new height
```
Undoubtedly there is a more elegant solution compared to this

**Comment by dhruvkb** [comment]
Since no better or more elegant solution has come up in the last two weeks, I'll send in a PR with the solution described above.

**Comment by janeatcc** [comment]
See https://github.com/creativecommons/cccatalog-frontend/issues/343

**Comment by brenoferreira** [comment]
We don't have that prevent overscaling checkbox anymore, so this is no longer relevant
