### ISSUE TITLE
Change language for social sharing buttons

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#271]
Keep link to provider (e.g. Flickr page hosting image) as the main link.

But the default suggested language for social media sharing needs to do a couple things:
- Make user aware of CC Search as a product
- Include reference to relevant CC social media account

So change to something like, "I found an image through CC search @creativecommons: [image link]” 

Open to suggestions for tweaks!

**Comment by janeatcc** [comment]
#165

**Comment by farouski** [comment]
I am interested in this but I have some questions? Would you want this text to change the Plain Text and Rich Text output on the catalog? Or would you like the HTML one to be changed as well? Or am I completely lost on what you are looking for.

Looking forward to contributing on this, 
Faris M.

**Comment by janeatcc** [comment]
This is regarding the social sharing buttons that are currently only live in the dev site. See https://github.com/creativecommons/cccatalog-frontend/issues/165

**Comment by farouski** [comment]
Ran into some small hiccups, getting it working on my local computer, (there were some issues with running it using npm both on my mac and my laptop using arch, but I got it working using docker, I will open an issue for this later). I also had to set the flag to enable social media sharing. Will attempt to solve this :)

**Comment by dhruvkb** [comment]
@farouski CC does not practice assigning of issues so you should start working on it now and submit a PR as soon as you're ready.

Also since the `Dockerfile` does very little apart from `npm install` the only plausible reason for it to not work outside of Docker that I can think of is a [Node version](https://github.com/creativecommons/cccatalog-frontend/blob/8d186a3fb7ac4c33adc89f3a3e556bb7a807e1f5/Dockerfile#L1) difference. Try seeing if your local Node version matches the one in the `Dockerfile`.

**Comment by farouski** [comment]
@dhruvkb I saw on the guidelines, to wait to be assigned. I have already completed this work, but I guess I might as well submit my PR right? I will also look into the npm differences. Thanks a lot for your help :)

**Comment by dhruvkb** [comment]
@farouski If someone else is assigned to an issue or if it has the 'In progress' label, you should probably wait for the other person to either solve it or be inactive for atleast a week. But seeing as no one is assigned and that 'Good first issue' is meant to introduce new people such as yourself to the codebase, your PR is more than welcome.

**Comment by brenoferreira** [comment]
#274 fixed this

**Comment by janeatcc** [comment]
Can we change "CC search" to "CC Search"? Small nit, but I'd like to make the Search more prominent in the text, esp since we're not linking back to the platform for this deploy.

Also, this text does not pop up for the FB option when I tested it. Should also read "I found an image through CC Search @creativecommons: https://www.flickr.com/photos/biodivlibrary/9240505252" for FB as well, currently just a link

**Comment by janeatcc** [comment]
Once the above changes have been made, we can push to prod and turn off feature flag.

**Comment by farouski** [comment]
I will attempt to see if I can get this done :)

**Comment by kgodey** [comment]
Marked as in progress.

**Comment by akowtko** [comment]
I'll look into this!

**Comment by akowtko** [comment]
@brenoferreira the PR is just to fix the capitalization. The issue with the Facebook sharer not loading the sharer text is due to Facebook only looking at meta tags. I listed some possibilities to fix this in the PR, but don't know how to test modifications to the meta tags. Do you have a staging environment? Or do you know how I can force the meta tags to evaluate on my dev server?

**Comment by brenoferreira** [comment]
@akowtko we use server side rendering to render the html, so there's no need to use `vue-meta`. You can see how we set meta tags [here](https://github.com/creativecommons/cccatalog-frontend/blob/develop/index-server.html)

**Comment by brenoferreira** [comment]
@akowtko For the Facebook text, can you open a new issue for that?

**Comment by akowtko** [comment]
@brenoferreira apologies for the delay. I filed a new issue here: https://github.com/creativecommons/cccatalog-frontend/issues/519.
