### ISSUE TITLE
filter drop-down for home page

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#297]
Adding to the home page the same filter UI that's available in the search results page

**Comment by hankolsen** [comment]
I'm interested in taking a look at this!

**Comment by kgodey** [comment]
go ahead @hankolsen

**Comment by hankolsen** [comment]
After thinking about this for a while, my suggestion is to add a "Advanced Search" link on the Home page:

![image](https://user-images.githubusercontent.com/1008390/56948834-a1955a00-6b31-11e9-8fad-d9fa7228215b.png)

(It should most likely be placed to the right closer to the magnifying glass button than in the screenshot) 


When the user clicks the Advanced-link, the Browse page is opened with the filter section expanded.

Adding the same filter component that is available on the Browse page will not work (technically), unless modified, since any change to the filter form will "reload" the Browse page. In the case of changing a filter form field on the Home page, the user will immediately end up on the Browse page which will be confusing.

Creating a new component for the Home page will be challenging from a design perspective. The width of all the filter component is much wider than the search input on the Home page so it will need some redesign. BUT most of all it will make the Home page more cluttered and not look as clean and simple. 


That's my conclusion after investigating this. I'm happy to receive comments and critique :)

**Comment by hankolsen** [comment]
The classic comparison:

![image](https://user-images.githubusercontent.com/1008390/56955043-9dbd0400-6b40-11e9-9d56-4c7f039b143f.png)

**Comment by janeatcc** [comment]
Interesting, thanks @hankolsen! I'm interested in @kgodey and @brenoferreira's feedback, as I think this is a priority item and people are missing the filters on the home page.

**Comment by kgodey** [comment]
I agree that hiding by default seems like the best option, it keeps things clean. I think we need a more polished design, though – maybe a second icon next to the search icon with a filter symbol or maybe a separate button?

**Comment by janeatcc** [comment]
Yes, hiding by default. But still want the drop-down to happen on the home page like it does on the search results page. Not sure if this is technically feasible as @hankolsen says

**Comment by hankolsen** [comment]
It is technically feasible, we just have to create a new component instead of re-using the exact one from the Browse page.

However, it does need a new design, since the width of the filter is much wider than the input field.
![image](https://user-images.githubusercontent.com/1008390/56989052-ccaf9600-6b91-11e9-844a-fd337cbaa2a8.png)

**Comment by janeatcc** [comment]
Got it. Let's aim for that then. I'll defer to @brenoferreira on how

**Comment by hankolsen** [comment]
Suggestion:
![SelectLicense](https://user-images.githubusercontent.com/1008390/57013640-ca3e5200-6c0c-11e9-8bcf-a4ba4cd942f2.png)
![SelectProvider](https://user-images.githubusercontent.com/1008390/57013641-ca3e5200-6c0c-11e9-8d6c-4a3df4621bfd.png)

**Comment by kgodey** [comment]
I'll defer to @janeatcc and @brenoferreira on the styling.

**Comment by janeatcc** [comment]
thank you @hankolsen ! I think @brenoferreira had some ideas about how this might work. I'll let him get back to you and come up with some mock-ups, etc.
