### ISSUE TITLE
license NULL text shows up on image page

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#299]
See: https://ccsearch.creativecommons.org/photos/5a12583c-8f12-4bf6-b202-25e6089941e9

"CC BY-NC-SA NULL"

**Comment by dhruvkb** [comment]
It appears that our API does not have license version information for this image at hand
```json
{
  "license": "by-nc-sa",
  "license_version": null
}
```

While this is a scraping issue _for this image, in particular at least,_ because the source mentions 4.0 explicitly, what version should we assume if none is specified? Is the latest license version, 4.0, backwards compatible with past licenses?
![image](https://user-images.githubusercontent.com/16580576/56406054-2314fe80-628d-11e9-81db-619f684dce97.png)

The non-versioned [link](https://creativecommons.org/licenses/by-nc-sa/) feels more like a 404 page rather than a page with links to the individual license versions.

**Comment by janeatcc** [comment]
This is a non-critical bug I'm moving to backlog for us to deal with. 

We can't supplement with license version manually b/c there is more than one license and the site's terms don't specify for more than one license. See: https://github.com/creativecommons/cccatalog/issues/149. And

**Comment by janeatcc** [comment]
@sclachar do we get images from this provider via API or common crawl?

**Comment by sclachar** [comment]
This is a Common Crawl provider.

**Comment by kgodey** [comment]
![Worm character puppet   Science Museum Group Collection](https://user-images.githubusercontent.com/287034/62171617-918e4180-b2fd-11e9-8ec3-beb4a8ab5cb9.png)

@sclachar the source page for this specifies 4.0 for the image so I think we should be able to save that information. what is the best way to do that – reprocess this entire provider?

**Comment by sclachar** [comment]
@kgodey the text specifies 4.0 however if you inspect the hyperlink you will see this provider does not correctly link to a license and that is the reason we are unable to extract the version.

**Comment by kgodey** [comment]
I emailed the Science Museum about this and I'll leave it assigned to me until they respond.

**Comment by annatuma** [comment]
@kgodey can you follow up with the Science Museum, and cc myself and @mathemancer into the thread, so we can try to get this sorted? I realize this isn't considered a critical bug but as general data cleanup it makes sense.

Also suggesting for the next sprint, so this stays on our radar, in case more follow-up is needed.

**Comment by annatuma** [comment]
Update: turns out this breaks the Collections page for the Science Museum, so while still not deemed critical, this is a higher priority to fix. Currently resulting in an error message when users search by collection.

![science museum collection search](https://user-images.githubusercontent.com/3051816/69987890-1d131b80-1506-11ea-9316-b04a497e9b2d.png)

cc @aldenstpage

**Comment by kgodey** [comment]
@annatuma I forwarded the email I sent them to you and @mathemancer. I never received a response.

**Comment by annatuma** [comment]
Closing this ticket, we're switching to an API integration:
https://github.com/creativecommons/cccatalog/issues/302

Note this same bug was reported in a separate ticket as well:
https://github.com/creativecommons/cccatalog/issues/244

That ticket has also been closed.
