### ISSUE TITLE
image grid search results -- explore whether this meets accessibility standards

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#328]
got feedback that this may cause motion sickness for a user. let's revisit post flip as part of backlog.

**Comment by dhruvkb** [comment]
Animations such as images sliding in and shuffling to rearrange can be eliminated fairly easily using
`transition-duration="0s"` instead of `transition-duration="0.3s"` (present value) in the `SearchGrid` component. The more important problem is to develop a user-friendly UX to allow them to opt-out of this animation.
