### ISSUE TITLE
Search page without Javascript

### ISSUE THREAD

**Issue by endlos99** [creativecommons/cccatalog-frontend#378]
**Describe the solution you'd like**
Enter the search query and show the results without relying on Javascript.  Even Google can do it!

**Comment by elharony** [comment]
Hi @endlos99 ,
Can you please describe the problem & solution?

**Comment by elharony** [comment]
Hi @endlos99 ,
Can you please give us more details about the problem & solution you suggest?

**Comment by endlos99** [comment]
*Problem:* Opening https://search.creativecommons.org/ with Firefox with JavaScript disabled (by NoScript) only shows an empty page.
*Solution:* Make https://search.creativecommons.org/ work without requiring JavaScript.

The same problem/solution apply to this results page, e.g., https://search.creativecommons.org/search?q=music.

**Comment by elharony** [comment]
Thanks for providing me with more info about this.
I wonder; Is there still a browser/device has a disabled JavaScript? I mean, do we REALLY need to fix such a problem who - almost - no one faces?

**Comment by endlos99** [comment]
Well, let me repeat that Google works perfectly fine without JavaScript.

**Comment by elharony** [comment]
Oh, I read that.
Did you read my previous comment?

**Comment by elharony** [comment]
Btw, Google still uses `positioned elements` with negative `margin` values to center an element... So, do we need to use the same approach to center a div inside another horizontally/vertically?

**Comment by endlos99** [comment]
I'm just asking for sane no-JavaScript fallback.  Your choice.

**Comment by elharony** [comment]
Well, it's not my choice at all - I am not the Project Maintainer, I am just a contributor who is trying to improve this project. So, no offense here! 😄 

Can you please talk a look and share your thoughts with us, @brenoferreira .

**Comment by brenoferreira** [comment]
We plan to do server side rendering for CC Search in the near future. We're running into some problems, and this is one of them, that can only be fixed by rendering pages on the server, in addition to doing client side rendering. But it's not something so trivial. Right now, the CC Search frontend is served simply by loading static assets from an Nginx server. There's no real backend that loads the assets. The backend right now is the CC Catalog API, but we have to keep both separate, as they are separate products (although they work together).

But thanks for the feedback @endlos99 and be sure that we will work on this.

**Comment by endlos99** [comment]
Awesome!

**Comment by brenoferreira** [comment]
An update on this:

We shipped the SSR rendering. So now, a few things work without Javascript.
But, currently, we use [this library](https://masonry.desandro.com/) to render search results. And this library isn't compatible with Node, which is what renders CC Search frontend on the server. So, you still won't be able to search without JS enabled.
I'll keep this issue open and we'll think about how we can solve this.
