### ISSUE TITLE
License types filter order and presentation

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#38]
The categories could be more specific, e.g. "commercial" should be "commercial use allowed". "Modification" should be "modification" allowed. Also, what if people want both commercial and modification allowed? A dropdown doesn't allow that. 

"all-cc" could be written "All Creative Commons" to be clearer. See Flickr's search interface filters at https://www.flickr.com/search/?text=cat. 

In general, like Flickr's search interface, filter categories should be capitalized and written so it is human readable.

**Comment by gargargarrick** [comment]
While it is a music site rather than a photo search engine, I might look to [Free Music Archive's search](http://freemusicarchive.org/search) for another good example. It uses checkboxes rather than a binary dropdown, so one can select multiple specific licenses or license categories. (I think allowing for both is useful -- I generally know the particular license I need, but not everyone does, and FMA's strategy makes it easy for both groups to find what they're looking for with minimal clicks.)

**Comment by sebworks** [comment]
@gargargarrick , thanks for the feedback. I've updated the filters with new text, please let me know if that works.

**Comment by sebworks** [comment]
this issue is now resolved.
