### ISSUE TITLE
External contributor process/guide for new features

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#407]
Draft (internal only): https://docs.google.com/document/d/1_biDhT1l_HNGM8xT5xccHocZ0KmvmpLH3-fZbgLk28E/edit#heading=h.2d275bfi1nb

**Comment by annatuma** [comment]
Next step is team review: should go from Alden to Breno to Sarah to Anna back to Kriti, and then be published.

**Comment by aldenstpage** [comment]
I like the idea of having a separate pipeline for major contributions and smaller bugfixes. I changed the order of the examples in step 0 to emphasize issues that don't require staff vetting. I also changed
>Any issue marked “help wanted” that does not explicitly specify that the issue needs product input or approval before coding begins.
to
>Any issue marked “help wanted”
since any ticket with the help wanted tag should be in a state that it is ready for outside contribution.

**Comment by aldenstpage** [comment]
Also, here's a similar contributing guide from a really successful OSS community: https://github.com/torproject/tor/blob/master/doc/HACKING/GettingStarted.md

**Comment by sarahpearson** [comment]
Looks very thorough to me! Good to go from my pov.

**Comment by annatuma** [comment]
Note to self: After I review, this goes back to Kriti.

**Comment by annatuma** [comment]
All set @kgodey, I left a handful of suggested edits but nothing major. Assigning back to you.
