### ISSUE TITLE
Allow users to share CC Search images without social media tracking

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#452]
Use something like https://github.com/heiseonline/shariff

**Comment by brenoferreira** [comment]
We don't insert any JS code provided by social platforms in the CC Search page. They're just links to their sharing APIs, as you can see [here](https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/SocialShareButtons.vue).
I don't think this issue is relevant in our case.

**Comment by kgodey** [comment]
okay great, thanks!
