### ISSUE TITLE
Improve Collections page (description, UI updates)

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#463]
We need to improve the overall UI of the Collections page. At present, the Collections page does not offer any context for what it is, nor does the current design work for a large number of Collections, which are anticipated in the coming months.

**Questions to guide the discussion**

What is our goal when it comes to collections?

What's the primary purpose of separating into collections?  Is it to increase visibility of images from high quality providers?  Help users find like-themed images?  Something else?

Given that purpose, how many collections would be appropriate to show?

Given that purpose, is it necessarily true that every image should be in a collection?  (That's our current model)

Some of our collections are providers, which in some cases are aggregators. For those, we are pulling out individual collections, known as sources. How (if at all) do we want to communicate the link between the Provider and the Source?

**Comment by annatuma** [comment]
We have the design for this slated for Q2. The content of the ticket may change.

**Comment by Dhruvi16** [comment]
Is this available to work on? I would love to take it up.
Thank you.

**Comment by annatuma** [comment]
@mathemancer I dropped your questions into the main ticket above, so help guide the discussion here.

@panchovm and I will be tackling this in the coming weeks, and will discuss proposals as they become available, so we can ensure that technical limitations/necessary changes are taken into account.

**Comment by panchovm** [comment]
In terms of purpose and goal, I advocate the idea of like-themed images. By doing this we are helping users to navigate through content when they don't have a specific keyword or sentence to search for.

That said, we can set the number of collections by looking at tags, categories, and any other type of meta-data that indicates themes. But that grouping might lies on us since we are grouping from different/cross sources.

Regarding the last point, I didn't understand the relationship between collections, providers, and aggregators.

**Comment by kgodey** [comment]
We're removing this page entirely. https://github.com/creativecommons/cccatalog-frontend/issues/1177
