### ISSUE TITLE
Ignore single instance of quote in search query

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#474]
Currently, if a user inputs a single instance of a double quote in their search term, they see an error. We should strip the quote character from their search term instead so that they can see results.

**Comment by qualitymanifest** [comment]
I'd like to give this one a try. I got searches with one doublequote working by adding a regex `match` and `replace` in `prepareSearchQueryParams.js`, but it leaves the quotation mark visible in the search box - should that be removed?

**Comment by qualitymanifest** [comment]
To remove the errant doublequote from the search box as well, it looks like this could go in [`setQuery`](https://github.com/creativecommons/cccatalog-frontend/blob/75b02ec383e602e1b4957e0c19571183eec6c9c8/src/store/search-store.js#L171). I tried it and it works. Just trying to figure a few things out:
1. Is that the best place to do that?
2. Is `params.query.q` guaranteed there, or can it be missing sometimes?
3. Should the [`trim` in `prepareSearchQueryParams`](https://github.com/creativecommons/cccatalog-frontend/blob/c31550561bab97e4cb7c58da75f158177b32f59a/src/utils/prepareSearchQueryParams.js#L6) also go in `setQuery`, so that it strips the spaces from the search box?

**Comment by kgodey** [comment]
tagging @brenoferreira

**Comment by brenoferreira** [comment]
I think this seems to me more like a bug on the API rather than on the frontend. API clients other the CC Search frontend will face the same problem

**Comment by kgodey** [comment]
That makes sense to me, tagging @aldenstpage to see what he thinks.

**Comment by aldenstpage** [comment]
It's not a bug but otherwise I agree that it would be better to help the user out a little bit if there are any unmatched quotes. See the above PR
