### ISSUE TITLE
Upgrade to CC Catalog API v1.0

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#551]
The 1.0 Release of the CC Catalog API is deployed. It has a few breaking changes compared to the old API, which will still be supported for a while, but not indefinitely. Therefore, we should update the frontend code to support this new version of the API.

The API documentation is available at https://api-dev.creativecommons.engineering/v1

All the calls to the API in the frontend are made in [this module](https://github.com/creativecommons/cccatalog-frontend/tree/develop/src/api).

**Comment by nilshah98** [comment]
Hello, is this issue still up for grabs?
If yes, I would like to work on it.

**Comment by brenoferreira** [comment]
Yes it is @nilshah98 

You're welcome to do it if you want

**Comment by nilshah98** [comment]
Hey, the link provided for api - [api-dev v1](https://api-dev.creativecommons.engineering/v1)  isn't working for me here.
Is there anywhere else I can access the documentation for the same?

**Comment by brenoferreira** [comment]
v1.0 is now available at https://api-dev.creativecommons.engineering/v1/. The old version is available at https://api.creativecommons.engineering/v0/ for comparison

**Comment by nilshah98** [comment]
Thanks a lot, I'll get started with the same.

**Comment by annatuma** [comment]
@nilshah98 I'll mark this in progress, feel free to make a pull request and start work.

**Comment by nilshah98** [comment]
The link - https://api-dev.creativecommons.engineering/v1/ isn't working, please can someone look into it.

**Comment by brenoferreira** [comment]
The API-DEV is a little unstable now. It will soon be resolved

**Comment by nilshah98** [comment]
Ok thanks, it's up now.
Will get back to working on it.

**Comment by kgodey** [comment]
API v1 will be more stable once https://github.com/creativecommons/cccatalog-api/pull/399 is merged and deployed.

**Comment by nilshah98** [comment]
Thanks a lot for the info @kgodey . Now, I know where to look at incase of a breakdown again.

**Comment by nilshah98** [comment]
Hey, I have few questions with regards to API and with regards to Frontend structure.

**API**
I can't seem to find documentation for the endpoints - 
- `/analytics/{event}` for `POST`
- `report-bug` for `POST`
Neither can I find them in v0.36 nor in v1.0

Also, in v0.36 there is `/image/browse/{provider}` endpoint, but there is no similar endpoint in v1, so should I just try using `/images?source=...` for them ?

---

**Frontend**
So, it took me a few days, but I have kind of got the hang of the structure for the Vue project. The question I have here is to make the project compatible with v1 of API, should I make changes to the `store` directly or make changes in `mixins` or `utils` to get it done?
Since, there are various method to go about it.

Currently, I have partially ported the `ImageService` API, but only made changes to `utils` or `mixins` and refrained from touching `store`

Can someone please, shed a light on it. Also if there's some developer guide to the frontend project, would be great.

Thanks.

**Comment by kgodey** [comment]
tagging @aldenstpage and @brenoferreira

**Comment by nilshah98** [comment]
I've made certain changes for handling `ImageService.js` at - [nilshah98/issue-551](https://github.com/nilshah98/cccatalog-frontend/tree/issue-551)

Do have a look, and provide inputs.

@brenoferreira @aldenstpage

**Comment by brenoferreira** [comment]
@nilshah98 please open a Pull Request. It's hard to see changes in your branch here https://github.com/nilshah98/cccatalog-frontend/tree/issue-551

**Comment by nilshah98** [comment]
Opened a PR at #570 .
Please review @brenoferreira
