### ISSUE TITLE
no search guide option in navbar while full screen 

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#636]
### while full screen:
![Screenshot from 2020-02-25 09-18-34](https://user-images.githubusercontent.com/54955755/75213715-013fae80-57b1-11ea-95a2-9c563659b4fb.png)

### In mobile view:
![Screenshot from 2020-02-25 09-18-23](https://user-images.githubusercontent.com/54955755/75213813-554a9300-57b1-11ea-82fc-16f40ac510f3.png)

## Additional context
if really its an issue,I would like to take this up.

**Comment by coderbabu10** [comment]
@brenoferreira

**Comment by akmadian** [comment]
This is because the "See our Search Syntax Guide here" link in the bottom right serves the same purpose, and is hidden on mobile, so the link in the header replaces it.

Also, please refrain from pinging Breno when opening new issues or pull requests. All of us mentors keep an eye on our repos. Please only ping when you haven't heard anything for three business days.

**Comment by coderbabu10** [comment]
oh sorry sir i will take care for the same
@akmadian
