### ISSUE TITLE
searching error

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#643]
## To Reproduce
1. select an image:
![Screenshot from 2020-02-25 21-56-53](https://user-images.githubusercontent.com/54955755/75269633-3be03000-581f-11ea-8558-b9d49e31bc3e.png)

2. now search for the other images:
![Screenshot from 2020-02-25 21-57-22](https://user-images.githubusercontent.com/54955755/75269987-d0e32900-581f-11ea-8248-27da549b549f.png)

3. Previous results are shown not the desired result:
![Screenshot from 2020-02-25 21-57-36](https://user-images.githubusercontent.com/54955755/75270010-dd678180-581f-11ea-931b-a5c07aa3c655.png)

## Expected behavior
it should show the desired results not the previous one

## Additional context
i would like to take this issue.

**Comment by DantrazTrev** [comment]
@coderbabu10 the issue already exists #616

**Comment by akmadian** [comment]
I'm closing this issue because it is a duplicate. 

@coderbabu10, please check to see if someone else has reported an issue before you, and please be sure to give your issues more descriptive titles. "searching error" could mean anything from improper results being fetched, to a visual bug, to a 400 or 500 error.
