### ISSUE TITLE
Guide link gets hidden under footer , when zoomed to 100% 

### ISSUE THREAD

**Issue by ankurshr01** [creativecommons/cccatalog-frontend#677]
On the localhost:8443 i.e home page, the guide link which is present on the bottom-right ,above the footer , gets hidden when zoomed to 100%. 
Screenshots : -
![Screenshot (178)](https://user-images.githubusercontent.com/43695296/75577639-6bde3c00-5a88-11ea-8108-ea6f7492a0a5.png)

![Screenshot (180)](https://user-images.githubusercontent.com/43695296/75577658-7567a400-5a88-11ea-8262-c906bd458bcf.png)

![Screenshot (179)](https://user-images.githubusercontent.com/43695296/75577669-7c8eb200-5a88-11ea-9ac9-9b08647cf9cd.png)

OS- Windows 10/ Ubuntu (checked on both ) 
Browser - Chrome(80.0.3987.122)

Will be working on this !

**Comment by abhisheknaiidu** [comment]
@ankurshr01 To be precise, the guide link gets hidden when its getting zoomed in between 110-125%

![c2](https://user-images.githubusercontent.com/55599878/75581935-87e5db80-5a90-11ea-9656-c7128d7e7604.png)


Above 125%, Its giving same results as normal 

![c3](https://user-images.githubusercontent.com/55599878/75581991-a3e97d00-5a90-11ea-93b4-dc13d1aae52e.png)

But I dont think so its actually an issue, because in every webpage, like if you take google's search page also, If we zoom their size, then there also some of their elements will get hidden to some extent. I guess its because of some CSS Distortions that are coming in the guide link div.

**Comment by ankurshr01** [comment]
@abhisheknaiidu check it with google chrome , even when its on 100% , the guide link gets hidden.

**Comment by abhisheknaiidu** [comment]
@ankurshr01 In my case, it's working fine only on 100% in Google Chrome Browser. 

![c4](https://user-images.githubusercontent.com/55599878/75587824-5de6e600-5a9d-11ea-991f-f757e8dc08aa.png)

**Comment by annatuma** [comment]
This seems likely to be impacted by the work @brenoferreira is doing on the grid (https://github.com/creativecommons/cccatalog-frontend/pull/661)

As such, we're marking this ticket as "not ready for work", until that pull request is closed.

If this is still an issue after the grid changes are live, we will mark it as open to community contribution. Thank you for your suggestion @ankurshr01

**Comment by akmadian** [comment]
This is still an issue after 661 was merged. @ankurshr01 if you'd like to work on this issue, you can go ahead and get started!

**Comment by abhisheknaiidu** [comment]
@akmadian If no one has shown interest on this, can I work on this :)

**Comment by ankurshr01** [comment]
@abhisheknaiidu I am working on this one !!

**Comment by brenoferreira** [comment]
With the new redesign this is no longer an issue. But thanks for your contribution
