### ISSUE TITLE
Hover Option should be provided to the license Icons to get better user experience.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#698]
## Describe the bug
Hover option is not there, when we hover over the license icons! 

## To Reproduce

1. Go to https://search.creativecommons.org/
2. Search any Image

## Expected behavior

Hover Option should be provided to the license Icons to get better user experience.

## Screenshots

![e1](https://user-images.githubusercontent.com/55599878/75749311-872a9f00-5d47-11ea-96bc-79c7b04af58b.png)

## Desktop (please complete the following information)
 - OS: Ubutu
 - Browser Firefox

## Additional context

If this issue is considered, then I would like to work on it :)

**Comment by akmadian** [comment]
I'm unsure what you mean by "hover", what do you think should happen when the icons are hovered over?

I've added `ticket work required` to give you the opportunity to elaborate :)

**Comment by hemanth-hk** [comment]
I think @abhisheknaiidu wanted to say that, It would be better if we get the info about the license when we hover over it

When I looked into it, each icon had a separate `alt` attribute so there would be no accessibility error and since the `main image` along with the `provider image` and the `license icons` are in the same `a` tag it's better to give the `main image's` title to the `title` attribute of the tag

**Comment by abhisheknaiidu** [comment]
@akmadian I just wanted to say what @hemanth-hk  has said, that,It would be better if we get the info about the licenses when we hover over it!

**Comment by akmadian** [comment]
I want to be sure that we're on the same page. The way I read this was that the license icons as a whole would have a single title attribute with the full license name, instead of the individual icons each having their own title. 

For example, if the license was "BY NC SA", instead of having each of the by, nc, and sa icons have their own title when hovered, the license icons as a group would have a single title with the full license name.

I'd like to get @panchovm's perspective on this RE accessability. Pending his approval, I think this would be a good idea, and I'll assign @abhisheknaiidu :)

**Comment by panchovm** [comment]
It is a good proposal, and it definitely improves accessibility. However, we are only considering, as hover interaction, showing the license icons and image's name in future implementations. But I do agree with showing the license name ( "BY NC SA") in the `alt` information. Hover inside hover is confusing and not suitable for responsiveness.

**Comment by hemanth-hk** [comment]
I think the present text in `alt` is enough to describe the icon

### Screenshots
![alt-license](https://user-images.githubusercontent.com/43946715/75989064-944ab800-5f18-11ea-9ef4-30211300f32b.jpg)

**Comment by abhisheknaiidu** [comment]
@hemanth-hk No it needs to have the exact license name like "BY NC SA", which @panchovm suggested, for better accessibilty! I mean that it should be attached to figcaption's section.

**Comment by akmadian** [comment]
Right, I think that you've got the right idea @abhisheknaiidu. Go ahead and start work on this :)
