### ISSUE TITLE
Hover at the logo of provider in the search grid cell displays the image text

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#704]
## Describe the bug
The hover text at provider logo should be the provider name

## To Reproduce

1. Search anything
2. hover over the logo of the provider on the image
3. You'll see the image text

## Expected behavior
Instead, there should be the provider name when hovered

## Screenshots

![image](https://user-images.githubusercontent.com/43457420/75771283-adfccb80-5d6f-11ea-94ee-e8d9074d3e3e.png)

## Desktop (please complete the following information)
 - OS: Windows 10
 - Browser Chrome
 - Version 80

## Additional context
I would like to work on this

**Comment by hemanth-hk** [comment]
If you click on the image and go to the `info tab` you can hover and get the name of the provider.
By hover, I think you mean the `title` property and that should be I think the name of the image right??

Do wait for the mentor's comment

**Comment by akmadian** [comment]
Thanks for spotting this :) I think this is intentional, and best from an accessibility standpoint. When the provider logo is clicked, it doesn't take you to flickr, it takes you to the image details page. Making the title different to the behavior would be bad for accessibility.

I'll defer to @brenoferreira to see if this is intentional. If it is, I think we should close this

**Comment by annatuma** [comment]
@DantrazTrev thanks for noting this. As @hemanth-hk has pointed out, there is indeed a discrepancy in what we show when hovering over the logo of the source.

On the results page, we show the title of the work.
![results-page-more-correct](https://user-images.githubusercontent.com/3051816/76026041-a82ff300-5ef3-11ea-952f-71d35ee42879.png)

On the single result page, we show the name of the source.
![single-results-page-incorrect](https://user-images.githubusercontent.com/3051816/76026039-a7975c80-5ef3-11ea-9b47-3a0b1f6217fb.png)

The best user experience would be the title _and_ the source. Therefore, we should fix this: 
Text on hover should be "[Title] at [Source]". In the example above, it would be "Spring Day at deviantart".

Ideally, though, we could pull the correctly formatted collection name. For instance, in the case of "Cleveland Museum of Art", our current hover text is "clevelandmuseum".

@DantrazTrev you are welcome to work on this, making the correction to both the results page, and the single result page. If you cannot find where to pull the correctly formatted collection name, please do not let that block you, but please do leave a comment here so that @brenoferreira can guide you to where that content is.

Thank you!

**Comment by AyanChoudhary** [comment]
@DantrazTrev are you working on this? If not I would like to work on this.

**Comment by akmadian** [comment]
@AyanChoudhary DantrazTrev only got the assignment a few days ago, so I'll leave it assigned to him for now. If no progress is made and he is unassigned, I'll assign it to you

**Comment by DantrazTrev** [comment]
Hi, I need help fetching the image source's formatted names , can you please guide me?

**Comment by akmadian** [comment]
Hey @DantrazTrev, I see that you opened a PR for this, do you still need help or did you figure it out?

**Comment by abhisheknaiidu** [comment]
After the new Design got merged, we are not showing the logo of the provider in the search grid cell, just showing the text content, So @akmadian @kgodey @brenoferreira this should be close now.

**Comment by brenoferreira** [comment]
Yes. After the redesign we're not showing the source logo in the grid. Thanks for the suggestion though
