### ISSUE TITLE
Add more social media share options

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#728]
## Problem Description
The current social media share options are quite limited and there are more platforms that are used more for sharing images than the current ones.

## Solution Description
So maybe we can add more like Tumblr, Instagram or famous image boards

## Alternatives
There could be an option in the Share tab that directs to more platforms to avoid UI congestion

## Additional context
If this qualifies I would like to work on it

**Comment by Siyubu** [comment]
I'm an outreachy applicant for May, 2020 intake and I would love to work on this project once it is ready for work

**Comment by annatuma** [comment]
@DantrazTrev you're welcome to propose a change to the Share tab. Please let us know which icons specifically you'd want to include. Please make use of FontAwesome icons, as that's what we'll be using on CC Search.

Before this change can be implemented on CC Search, however, we'll need to add the additional social media icons into Vocabulary. @DantrazTrev please create a ticket for that and work on it before this one. Please comment on this ticket to confirm the ticket you've created in Vocabulary, so workflow can be tracked.

Separately - it is possible we don't need these in the Design Library, since they are FontAwesome, but @panchovm and I will review that.

**Comment by annatuma** [comment]
After internal discussion on this, we've decided not to move forward with expanding social media icon son the Share tab, but are likely to end up removing that tab entirely in the future, when we reimagine the single results page. The usage rate of social media sharing of images from CC Search is so low it doesn't warrant built-in support.
