### ISSUE TITLE
Components of Filter Button should open downwards, not upwards in mobile view for better responsiveness

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#738]
## Describe the bug
Components of Filter Button should open downwards, not upwards in mobile view for responsiveness

## To Reproduce

1. Go to https://search.creativecommons.org/
2. Go to Mobile View
3. Click Filter Button 

## Expected behavior
Filter button should open downwards, not upwards for better responsiveness.

## Screenshots

![mobi](https://user-images.githubusercontent.com/55599878/76248902-4ad7d100-6268-11ea-87d6-078351be4c23.png)

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Chrome

## Additional context
Want to work on this, if it's a legit issue :)

**Comment by annatuma** [comment]
@abhisheknaiidu we have an upcoming UI change planned for filters on mobile, where the filters would essentially function like a modal (overlaying results), and the user would need to press "show results" (new button) or close the modal (x in top right hand corner), in order to see results. This is part of the work @brenoferreira is doing for Design Sprint 1. Therefore, I'm not sure it's worth the time to work on this further.
