### ISSUE TITLE
Unnecessary Calling of two lifecycle hooks in SearchGrid Component, adding and removing can be done inside just the mounted method only

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#744]
## Describe the bug
When adding/deleting component event listeners in Vue, we use the lifecycle hooks mounted and beforeDestroy. **beforeDestroy** hook causes memory leaks if any. In the typical pattern, we would have to declare these hooks separately in the component options object. One problem with this is that with larger components, these options can be hundreds of lines apart.
Looking at the Vue docs, we see that there is an instance method $on that listens for instance events.The event name is the “hook:” + name of the hook itself (e.g. hook:created)

## Expected behavior
Before :

  mounted() {
    document.addEventListener('scroll', this.checkScrollLength);
  },
  beforeDestroy() {
    document.removeEventListener('scroll', this.checkScrollLength);
  }

After :

mounted () {
    document.addEventListener('scroll', this.checkScrollLength);
    this.$on("hook:beforeDestroy", () => {
      document.removeEventListener('scroll', this.checkScrollLength);
    })
}

**This means we don’t have to define another lifecycle hook. Something that can greatly increase code readability.**

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Chrome

## Additional context
Want to work on this :)

**Comment by hemanth-hk** [comment]
I think before one is good. It's like the ternary operator and the if statement, for the code-base to be beginner-friendly I think the before is better

Do wait for others view-point

**Comment by abhisheknaiidu** [comment]
@hemanth-hk calling two life-cycle hooks is not so great than calling just a single lifecycle hook,With single life-cycle hook, It increases the code readability. and btw also the beforeDestroy hook causes memory leaks! so it also diminishes that also.

**Comment by akmadian** [comment]
Thanks for suggesting this :) I think that the readability of what we have now is better. It's far easier IMO to understand exactly what the code is doing at a glance than the proposed syntax.

I'm going to close this issue because I don't think this change is necessary, although I am curious about the memory leaks. Please find some resources or articles, maybe a stackoverflow thread or other documentation of the link between the beforeDestroy hook and memory leaks, and open a new issue for the specific issue of memory leaks with those resources linked.
