### ISSUE TITLE
 giving link title in footer for better accessibility.

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#751]
## Problem Description
we can add link title in footer for better accessibility,as it will help the user to know the given links in more clear way.

## Solution Description
we can add the title tag for the links.

## Additional context
i would like to take this up.

**Comment by abhisheknaiidu** [comment]
@coderbabu10 Actually this footer is temporary, and will be overwritten once the actual footer component will get ready in vocab.So this issue should be closed, because it does not affect any functionality, and would be quickly overwritten in the transition to vocab.

**Comment by coderbabu10** [comment]
Yeah @abhisheknaiidu i know that the footer is temporary but we can have it as a suggestion that we can add this feature in future for better accessibility i want to know that what @akmadian and @brenoferreira have their views for this?

**Comment by akmadian** [comment]
Thanks for suggesting this :) If by link title you mean a title above the links that says "Links", I don't think this is necessary. I'm gonna go ahead and close this since the current footer is going to be deprecated soon in favor of the Vocab footer component.

If you would like to propose the addition to vocabulary, you can go ahead and open an issue [in the vue-vocabulary repo](https://github.com/creativecommons/vue-vocabulary) with your proposal for the addition.
