### ISSUE TITLE
In social media icons are not the same as the mockup.

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#809]
In the single result page, **Share** tab, the social media icons should be the icons available in the mockup.

### Expected design
<img width="599" alt="Screen Shot 2020-03-24 at 17 58 29" src="https://user-images.githubusercontent.com/895819/77476297-154eee00-6df9-11ea-93fc-e3ebf20cf411.png">

**Comment by abhisheknaiidu** [comment]
Want to work on this :)

**Comment by Rishabh606** [comment]
@panchovm you mean to say icons in share tab of actual website's search result. I am attaching the screenshot for confirmation. 
![Screenshot from 2020-03-26 09-24-29](https://user-images.githubusercontent.com/29687025/77651741-9d410f00-6f43-11ea-9338-e0533f23983b.png)
The image on the right side is the target and left side demonstrates above picture. 
Though I am a bit confused as to what's wrong in the icons on the right? It's just a bit different but adequately represents their respective functions.
P.S. - Since I am new to this repo, kindly ignore if this is a stupid question.

**Comment by panchovm** [comment]
On the right image, the functionality is correct; it works. This update is regarding updating the branding guidelines. The left image has the last version of logos.

**Comment by brenoferreira** [comment]
This is fixed in #850
