### ISSUE TITLE
Fix CSS bundle in webpack

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#829]
The current webpack config has some strange behaviour. The dev bundle and the production bundle seem different.

In the production bundle, the fontend component styles come before the Vocabulary styles, which mess up the CSS styles precedence order. The dependency's styles should come before the custom styles of the frontend components. This seems to be the case in the dev bundle but not in the production bundle. Not sure why.

It also seems that importing individual .scss from Vocabulary causes webpack to include its styles a bunch of times in the generated .css bundle. Also not sure why that happens.

**Comment by vane** [comment]
It's due to `MiniCSSExtractPlugin` bugs. Dev is using `vue-style-loader`.

**Comment by vane** [comment]
Ok ignore my last comment it's due to how css specificity works so I didn't dig into vue-style-loader but it probably works only cause of hot replacement feature. 
if you just use `.button.rating` you can get rid of !important. 
More about css styles rating here https://htmldog.com/guides/css/intermediate/specificity/
