### ISSUE TITLE
Prior filter(s) not clearing when new search initiated from homepage

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#896]
## Describe the bug
If we search something then go back to the homepage , and then search something else the filter is still applied only superficially and isn't doing anything

## To Reproduce

1. Search something
2.Apply a filter
3. Go back to homepage using the back button of the browser
4. Search for something else
5. See the results are still with filter applied although superficial

## Expected behavior
Either the filters must be cleared totally or the browser must be applied fully and not just rendering previous results 

## Screenshots
![#1](https://user-images.githubusercontent.com/43457420/80313253-6e021400-8807-11ea-9a0a-e00a4c8a141e.png)

![#2](https://user-images.githubusercontent.com/43457420/80313266-7ce8c680-8807-11ea-8f2b-4e5ae0df5ee3.png)

## Desktop 
 - OS: macOS 10.15
 - Browser: Safari
 - Version :13.0.2

**Comment by dos077** [comment]
Cannot replicate the bug on Chrome 81. Must be a Safari specific bug. Unfortunately I can't help testing it, since I don't have a Mac.

**Comment by annatuma** [comment]
Replicated on Safari Version 13.0.5 (15608.5.11) and Firefox 74.0.1 on Mac OS.

The correct behavior would be:
1. User enters search query on homepage.
2. User views results, applies filter.
3. User presses "Back" button to return to homepage.
4. User enters new search query on homepage.
5. No filters are applied on results page, i.e. filters have been cleared given that it is a brand new search originating from the homepage.

Thanks for reporting this @DantrazTrev I'm flagging this for community contribution.

**Comment by vane** [comment]
It's because of filter modifies url and back button returns filter to previous state.
Filter store state should be adjusted after every back button click in `clientEntry.js` method `beforeRouteUpdate`.

**Comment by Fahme** [comment]
@annatuma to extend on the issue i think also navigating from the collections page to search results page is a case should be handled what i.e. is : 

1. go to ``/collections``
2. Press any of the collections providers.
3. redirects to search results
4. apply filter 
5. press back button 

expected  to redirects into the ``/collections``.

**Comment by Fahme** [comment]
@vane thanks for giving the pointers however i've did some more debugging and found out the root cause it's due to the global mixin here https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/clientEntry.js#L13 ``beforeRouteUpdate`` which is  effecting every level in the application component. 

My reasoning is that the ``next()`` func is not canceled correctly (aborted) which will make make it alway look for the next hook in the chain and so a fix for now would be to change it to ``next(false)`` in order to abort the hook.

This definlty solved the bug, however i don't feel this is clean enough and i prefer a cleaner way to fix this by refactoring the mixing and defining ``beforeRouteUpdate()`` on every component level that needs the hook instead of defining it globally like that.

I'm still new to this codebase so any help from @annatuma would be appreciated !

**Comment by Fahme** [comment]
@annatuma this should be solved by https://github.com/creativecommons/cccatalog-frontend/pull/929 however while fixing this i noticed a bug which could be related :

1. User type a search query in homepage
2. User gets Redirected to results page
3. User applies two~three filters
4. User press back button 

Current : 
The browser url changes, however the content of the page won't change

expected : 

The content should change based on the url and query param ?
