### ISSUE TITLE
Accessibility - Improve labels

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#996]
During the audit of CC Search with Accessibility tools such as Lighthouse, we found that many of our pages don't have good labels for screen readers. That includes

* Labels for inputs on forms
* Aria labels and roles on elements such as buttons
* The vocabulary icons are now rendered with fonts and probably don't work well with screen readers. We need to add aria labels to those too

These labels will have to be internationalized, once the i18n project is setup

**Comment by dos077** [comment]
All of the input and button elements are just plain HTML tags, as far as I can tell. It will just take a bit of elbow grease to add aria label to all of them, but looking into the vocabulary, it seems like creativecommons is building and migrating its website into a common reusable UI component library? In that case editing the plain HTML tags now will be a waste of effort, since they will be replaced by custom components. Personally I think using any reusable component library is superior to just plain HTML tags.
